dataSource:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: ip_sys_rw
  # the password
  password: caiP5yaa
  # the JDBC URL
  url: jdbc:mysql://10.32.225.159/erp_inv_db_test?rewriteBatchedStatements=true
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 50
  # the maximum number of connections to keep open
  maxSize: 200
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true
  # how long a connection must be held before it can be validated
  validationInterval: 10s
  # the maximum lifetime of an idle connection
  minIdleTime: 1 minute
  # the maximum lifetime of an idle connection
  maxConnectionAge: 1 minute
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

rotationManagementConfig:
  persistantFilePath: "/var/run/fk-ip-inventory-planner/persistant_state.txt"

logging:
  level: INFO
  loggers:
    "org.hibernate.ejb.HibernatePersistence": INFO
    "org.hibernate.SQL": INFO
    "org.hibernate.type": INFO
    "com.flipkart.mmq.Dispatcher": INFO
  appenders:
  - type: file-size-rolled
    threshold: ALL
    timeZone: Asia/Calcutta
    logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %replace(%c: %m){'\n', '\n '}%n%replace(%ex){'(?m)^(.)',' $1'}%nopex"
    currentLogFilename: /var/log/flipkart/rp/fk-ip-inventory-planner/production.log
    archive: true
    archivedLogFilenamePattern: /var/log/flipkart/rp/fk-ip-inventory-planner/production.%i.log.gz
    archivedFileCount: 4
    maxFileSize: 500MB

server:
  applicationConnectors:
  - type: http
    port: 32000
    acceptQueueSize: 0
  adminConnectors:
  - type: http
    port: 32001
  gzip:
    enabled: true
    minimumEntitySize: 256 bytes
    bufferSize: 8KiB
    excludedUserAgents: []
    compressedMimeTypes: []
  requestLog:
    timeZone: IST
    appenders:
    - type: file
      logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %replace(%c: %m){'\n', '\n '}%n%replace(%ex){'(?m)^(.)',' $1'}%nopex"
      currentLogFilename: /var/log/flipkart/rp/fk-ip-inventory-planner/requests.log
      archive: true
      archivedLogFilenamePattern: /var/log/flipkart/rp/fk-ip-inventory-planner/requests.%i.log.gz
      archivedFileCount: 2
      maxFileSize: 500MB


zuluConfiguration:
  url: http://10.47.1.8:31200
  viewPath: "/views"
  clientId: "retail.rp"
  maxBatchSize: 30

sslClientConfiguration:
  url: http://10.85.52.106
  viewPath: "/supplier_selection"
  batchSize: 10

fdpConfiguration:
  url: http://10.47.2.122:28223/ingestion/objects
  queueName: "fdp_requirement_ingestion"
  org: "/retail"
  company: "/fki"
  namespace: "/ip"
  requirementEntitySchemaVersion: "3.0"
  requirementEventSchemaVersion: "2.0"

procClientConfiguration:
  url: http://10.85.52.17
  viewPath: "/requirements"
  callbackUrl: http://10.85.110.102:32000/v1/requirement/callback/
  requirementQueueName: proc_b2b_production

clientConfiguration:
  timeout: 80000ms
  connectionTimeout: 50000ms
  connectionRequestTimeout: 50000ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0s
  minThreads: 1
  maxThreads: 128
  gzipEnabled: false
  gzipEnabledForRequests: false
  chunkedEncodingEnabled: false

triggerRequirementConfiguration:
  url: http://10.85.53.212/v1/requirement
  projectionQueueName: retail_rp_internal_projection
  fetchDataBatchSize: 10000
  createReqBatchSize: 10

connektConfiguration:
  url: http://10.47.4.150:80/v1/send/email/flipkart-promo
  x-api-key: BM9kig6BGwN68aeJG2ESWkxt8

emailConfiguration:
  host: 10.85.169.122:39001
  path: "/projection/"

d42Configuration:
  accessKey: "EKBK5XNIHLM7E3290RBX"
  secretKey: "QGXi9BkrIArIb255tHRFR7trEcPSvxBi3X0LsBwP"
  url: "http://10.47.2.2"

groupSegmentationConfiguration:
  url: http://10.85.110.102:32000/v1/group
  queueName: retail_ip_group_segmentation


